<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/bootstrap.php';
$auth->requireLogin();
function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$role=(string)$auth->role(); $userId=(int)$auth->id(); $sessionOfficeId=(int)($auth->officeId()??0); $loggedInAgentId=null;
if($role==='agent'){
 $s=$db->prepare('SELECT id,office_id FROM agents WHERE user_id=:u AND deleted_at IS NULL AND is_active=1 LIMIT 1'); $s->execute(['u'=>$userId]); $a=$s->fetch(); if(!$a){http_response_code(403);exit('No active agent profile is linked to this user.');} $loggedInAgentId=(int)$a['id']; $sessionOfficeId=(int)$a['office_id'];
}
$csrf=\App\Csrf::token(); $error='';
$canCreate=in_array($role,['super_admin','office_admin','agent'],true); $canDelete=in_array($role,['super_admin','office_admin','agent'],true);
$offices=[]; if($role==='super_admin') $offices=$db->query('SELECT id,name FROM offices WHERE deleted_at IS NULL AND is_active=1 ORDER BY name')->fetchAll();
$agents=$db->query('SELECT id,office_id,first_name,last_name FROM agents WHERE deleted_at IS NULL AND is_active=1 ORDER BY last_name,first_name')->fetchAll();
$propertyTypes=$db->query('SELECT id,code,name_key FROM property_types WHERE is_active=1 ORDER BY sort_order,code')->fetchAll();
$where=['p.deleted_at IS NULL']; $params=[];
if($role==='office_admin'){ $where[]='p.office_id=:office'; $params['office'] = $sessionOfficeId; }
elseif($role==='agent'){ $where[]='p.agent_id=:agent'; $params['agent']=$loggedInAgentId; }
$q=trim((string)($_GET['q']??'')); if($q!==''){ $where[]='(p.reference LIKE :q OR p.title LIKE :q OR p.city LIKE :q)'; $params['q']='%'.$q.'%'; }
$status=trim((string)($_GET['status']??'')); if(in_array($status,['draft','active','sold','rented','withdrawn'],true)){ $where[]='p.status=:status'; $params['status']=$status; }
$sql='SELECT p.id,p.reference,p.title,p.status,p.transaction_type,p.price,p.currency_code,p.city,p.living_area_m2,p.bedrooms,p.is_featured,p.is_published,o.name office_name,CONCAT(a.first_name," ",a.last_name) agent_name,pt.code property_type_code,pm.file_path primary_photo FROM properties p INNER JOIN offices o ON o.id=p.office_id LEFT JOIN agents a ON a.id=p.agent_id LEFT JOIN property_types pt ON pt.id=p.property_type_id LEFT JOIN property_media pm ON pm.property_id=p.id AND pm.is_primary=1 AND pm.deleted_at IS NULL WHERE '.implode(' AND ',$where).' ORDER BY p.created_at DESC,p.id DESC';
$s=$db->prepare($sql); $s->execute($params); $properties=$s->fetchAll();
?><!doctype html><html lang="<?=e($i18n->getLanguage())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(__t('properties.title','Properties'))?> - Immo</title><style>
:root{--bg:#f5f7fb;--card:#fff;--border:#e4e7ec;--text:#172033;--muted:#667085;--primary:#111827;--green:#067647;--red:#b42318;--blue:#175cd3}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:1450px;margin:auto;padding:28px 22px 60px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:22px}.top h1{margin:0;font-size:30px;letter-spacing:-.02em}.muted{color:var(--muted);font-size:13px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a,.btn{display:inline-flex;align-items:center;justify-content:center;padding:9px 13px;border-radius:9px;border:1px solid var(--border);background:#fff;color:var(--text);text-decoration:none;font-size:14px;cursor:pointer}.nav a.active,.btn.primary{background:var(--primary);color:#fff;border-color:var(--primary)}.btn.danger{color:var(--red);border-color:#fecdca;background:#fff}.card{background:#fff;border:1px solid var(--border);border-radius:14px;padding:20px;margin-bottom:20px;box-shadow:0 2px 8px rgba(16,24,40,.04)}.toolbar{display:flex;align-items:end;justify-content:space-between;gap:15px;flex-wrap:wrap}.filters{display:flex;gap:9px;flex-wrap:wrap}input,select{padding:10px 11px;border:1px solid #d0d5dd;border-radius:9px;background:#fff;font:inherit;color:var(--text)}.filters input{width:280px}.filters select{width:150px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1150px}th,td{text-align:left;padding:12px;border-bottom:1px solid #eef0f3;font-size:14px;vertical-align:middle}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em;background:#fafbfc}.property-cell{display:flex;gap:12px;align-items:center}.thumb{width:76px;height:58px;border-radius:8px;object-fit:cover;background:#eef0f3;flex:none}.thumb.empty{display:flex;align-items:center;justify-content:center;color:#98a2b3;font-size:11px}.ref{font-weight:750}.title{font-weight:650}.price{font-weight:750;white-space:nowrap}.pill{display:inline-flex;border-radius:999px;padding:4px 8px;font-size:12px;font-weight:650}.pill.draft{background:#f2f4f7;color:#344054}.pill.active{background:#ecfdf3;color:#067647}.pill.sold,.pill.rented{background:#eff8ff;color:#175cd3}.pill.withdrawn{background:#fef3f2;color:#b42318}.actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.actions form{margin:0}.empty{text-align:center;padding:45px;color:var(--muted)}.help{margin:4px 0 0;color:var(--muted);font-size:13px}@media(max-width:700px){.wrap{padding:18px 12px 40px}.top{flex-direction:column}.filters input,.filters select{width:100%}}
</style></head><body><div class="wrap"><div class="top"><div><h1><?=e(__t('properties.title','Properties'))?></h1><p class="help"><?=e(__t('properties.subtitle','Manage properties, edit details and manage photos from one place.'))?></p></div><nav class="nav"><a href="/immobilier/">Dashboard</a><?php if($role==='super_admin'):?><a href="/immobilier/admin/offices.php">Offices</a><?php endif;?><a href="/immobilier/admin/agents.php">Agents</a><a class="active" href="/immobilier/admin/properties.php">Properties</a></nav></div>
<div class="card"><div class="toolbar"><div><strong><?=e(__t('properties.list','Property portfolio'))?></strong><div class="help"><?=count($properties)?> <?=e(__t('properties.results','properties'))?></div></div><form method="get" class="filters"><input name="q" value="<?=e($q)?>" placeholder="<?=e(__t('properties.search','Search reference, title or city'))?>"><select name="status"><option value=""><?=e(__t('properties.all_statuses','All statuses'))?></option><?php foreach(['draft','active','sold','rented','withdrawn'] as $x):?><option value="<?=$x?>" <?=$status===$x?'selected':''?>><?=e(ucfirst($x))?></option><?php endforeach;?></select><button class="btn primary" type="submit">Filter</button><?php if($q!==''||$status!==''):?><a class="btn" href="/immobilier/admin/properties.php">Reset</a><?php endif;?></form></div></div>
<div class="card"><div class="table-wrap"><table><thead><tr><th>Property</th><th>Office</th><th>Agent</th><th>Price</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php if(!$properties):?><tr><td colspan="7"><div class="empty">No properties found.</div></td></tr><?php else: foreach($properties as $p):?><tr><td><div class="property-cell"><?php if($p['primary_photo']):?><img class="thumb" src="<?=e('/immobilier/'.ltrim($p['primary_photo'],'/'))?>" alt=""><?php else:?><div class="thumb empty">No photo</div><?php endif;?><div><div class="ref"><?=e($p['reference'])?></div><div class="title"><?=e($p['title']?:'Untitled property')?></div><div class="muted"><?=e($p['property_type_code']??'—')?> · <?=e($p['city']?:'No city')?></div></div></div></td><td><?=e($p['office_name'])?></td><td><?=e($p['agent_name']?:'Unassigned')?></td><td class="price"><?= $p['price']!==null?number_format((float)$p['price'],0,',',' ').' €':'—'?><div class="muted"><?=e(ucfirst((string)$p['transaction_type']))?></div></td><td><?= $p['living_area_m2']!==null?e($p['living_area_m2']).' m²':'—'?><div class="muted"><?= $p['bedrooms']!==null?(int)$p['bedrooms'].' bed':''?></div></td><td><span class="pill <?=e((string)$p['status'])?>"><?=e(ucfirst((string)$p['status']))?></span><?php if((int)$p['is_published']===1):?><div class="muted">Published</div><?php endif;?></td><td><div class="actions"><a class="btn primary" href="/immobilier/admin/property-edit.php?id=<?= (int)$p['id'] ?>">Edit</a><a class="btn" href="/immobilier/admin/property-edit.php?id=<?= (int)$p['id'] ?>#photos">Photos</a><?php if($canDelete):?><form method="post" action="/immobilier/admin/property-delete.php" onsubmit="return confirm('Delete this property? This will remove it from the active property list.');"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="property_id" value="<?= (int)$p['id'] ?>"><button class="btn danger" type="submit">Delete</button></form><?php endif;?></div></td></tr><?php endforeach; endif;?></tbody></table></div></div>
<?php if($canCreate):?><div class="card"><a class="btn primary" href="/immobilier/admin/property-create.php">+ <?=e(__t('properties.create','Create property'))?></a></div><?php endif;?></div></body></html>
