<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/bootstrap.php';
$auth->requireLogin();
function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function uuidv4(): string { $d=random_bytes(16); $d[6]=chr((ord($d[6])&15)|64); $d[8]=chr((ord($d[8])&63)|128); return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4)); }
$role=(string)$auth->role(); $userId=(int)$auth->id(); $officeId=(int)($auth->officeId() ?? 0);
$propertyId=(int)($_GET['id'] ?? $_POST['property_id'] ?? 0); if($propertyId<1){http_response_code(400);exit('Invalid property.');}
$agentContextId=null;
if($role==='agent'){
 $s=$db->prepare('SELECT id,office_id FROM agents WHERE user_id=:u AND deleted_at IS NULL AND is_active=1 LIMIT 1'); $s->execute(['u'=>$userId]); $a=$s->fetch();
 if(!$a){http_response_code(403);exit('No active agent profile.');} $agentContextId=(int)$a['id']; $officeId=(int)$a['office_id'];
}
function loadProperty(PDO $db,int $id): ?array {
 $s=$db->prepare('SELECT p.*,o.name office_name,CONCAT(a.first_name," ",a.last_name) agent_name,pt.code property_type_code,pt.name_key property_type_name_key FROM properties p INNER JOIN offices o ON o.id=p.office_id LEFT JOIN agents a ON a.id=p.agent_id LEFT JOIN property_types pt ON pt.id=p.property_type_id WHERE p.id=:id AND p.deleted_at IS NULL LIMIT 1');
 $s->execute(['id'=>$id]); return $s->fetch() ?: null;
}
$p=loadProperty($db,$propertyId); if(!$p){http_response_code(404);exit('Property not found.');}
if($role==='office_admin' && (int)$p['office_id']!==$officeId || $role==='agent' && ((int)$p['office_id']!==$officeId || (int)$p['agent_id']!==$agentContextId)){http_response_code(403);exit('Access denied.');}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['save_property'])){
 try{
  \App\Csrf::verify($_POST['_csrf']??'');
  $allowed=['reference','status','transaction_type','title','description','price','living_area_m2','land_area_m2','bedrooms','bathrooms','year_built','address_line_1','address_line_2','postcode','city','region'];
  $v=[]; foreach($allowed as $k){$v[$k]=trim((string)($_POST[$k]??'')); $v[$k]=($v[$k]==='')?null:$v[$k];}
  if($v['reference']===null) throw new RuntimeException(__t('properties.error.reference','Reference is required.'));
  if(!in_array($v['status'],['draft','active','sold','rented','withdrawn'],true)) throw new RuntimeException(__t('properties.error.status','Invalid status.'));
  if(!in_array($v['transaction_type'],['sale','rent'],true)) throw new RuntimeException(__t('properties.error.transaction','Invalid transaction type.'));
  $hasPool=isset($_POST['has_pool'])?1:0; $featured=isset($_POST['is_featured'])?1:0; $published=isset($_POST['is_published'])?1:0;
  if($role==='agent') $published=0;
  $s=$db->prepare('UPDATE properties SET reference=:reference,status=:status,transaction_type=:transaction_type,title=:title,description=:description,price=:price,living_area_m2=:living_area_m2,land_area_m2=:land_area_m2,bedrooms=:bedrooms,bathrooms=:bathrooms,year_built=:year_built,has_pool=:has_pool,address_line_1=:address_line_1,address_line_2=:address_line_2,postcode=:postcode,city=:city,region=:region,is_featured=:is_featured,is_published=:is_published,published_at=CASE WHEN :published=1 AND published_at IS NULL THEN NOW() WHEN :published=0 THEN NULL ELSE published_at END WHERE id=:id AND deleted_at IS NULL');
  $v['has_pool']=$hasPool;$v['is_featured']=$featured;$v['is_published']=$published;$v['id']=$propertyId;$v['published']=$published;$s->execute($v);$message=__t('properties.saved','Property saved successfully.');$p=loadProperty($db,$propertyId);
 }catch(Throwable $x){$error=$x->getMessage();}
}
$mediaStmt=$db->prepare('SELECT id,public_id,original_filename,file_path,thumbnail_path,medium_path,large_path,alt_text,sort_order,is_primary,mime_type,file_size,width,height FROM property_media WHERE property_id=:p AND deleted_at IS NULL ORDER BY sort_order,id');$mediaStmt->execute(['p'=>$propertyId]);$media=$mediaStmt->fetchAll();
$csrf=\App\Csrf::token();
?><!doctype html><html lang="<?=e($i18n->getLanguage())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($p['reference'])?> · <?=e(__t('properties.edit','Edit property'))?></title><style>
:root{--bg:#f5f7fb;--card:#fff;--border:#e4e7ec;--text:#172033;--muted:#667085;--primary:#111827;--green:#067647;--red:#b42318}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{max-width:1400px;margin:auto;padding:28px 22px 60px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.top h1{margin:0;font-size:28px}.muted{color:var(--muted);font-size:13px}.card{background:#fff;border:1px solid var(--border);border-radius:14px;padding:22px;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.span4{grid-column:1/-1}.span2{grid-column:span 2}label{display:block;font-size:13px;font-weight:650;margin-bottom:6px}input,select,textarea{width:100%;padding:10px;border:1px solid #d0d5dd;border-radius:9px;font:inherit}textarea{min-height:130px;resize:vertical}.actions{display:flex;gap:10px;margin-top:18px}button{border:0;border-radius:9px;padding:10px 15px;background:var(--primary);color:#fff;font-weight:650;cursor:pointer}button.secondary{background:#fff;color:var(--text);border:1px solid var(--border)}.notice,.error{padding:12px;border-radius:10px;margin-bottom:16px}.notice{background:#ecfdf3;color:var(--green)}.error{background:#fef3f2;color:var(--red)}.check{display:flex;gap:8px;align-items:center;margin-top:26px}.check input{width:auto}.media-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.media{border:1px solid var(--border);border-radius:12px;overflow:hidden;background:#fff;position:relative}.media.primary{outline:2px solid #111827}.media img{display:block;width:100%;height:190px;object-fit:cover;background:#eee}.media-body{padding:10px}.media-body input{margin:5px 0}.media-actions{display:flex;gap:6px;flex-wrap:wrap}.media-actions form{margin:0}.upload{border:2px dashed #cbd5e1;border-radius:12px;padding:24px;text-align:center;margin-bottom:18px}.upload input{border:0;padding:10px}.drag{cursor:grab}.badge{display:inline-block;background:#111827;color:#fff;border-radius:999px;padding:4px 8px;font-size:11px;position:absolute;top:8px;left:8px}@media(max-width:1000px){.grid,.media-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.grid,.media-grid{grid-template-columns:1fr}.span2,.span4{grid-column:auto}.top{flex-direction:column}}
</style></head><body><div class="wrap"><div class="top"><div><div class="muted"><a href="/immobilier/admin/properties.php">← <?=e(__t('common.back','Back to properties'))?></a></div><h1><?=e($p['reference'])?></h1><div class="muted"><?=e($p['title']??'')?></div></div><div class="muted"><?=e($p['office_name'])?> · <?=e($p['agent_name']??__t('properties.unassigned','Unassigned'))?></div></div>
<?php if($message):?><div class="notice"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="error"><?=e($error)?></div><?php endif;?>
<div class="card"><h2><?=e(__t('properties.details','Property details'))?></h2><form method="post"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="property_id" value="<?=$propertyId?>"><div class="grid">
<div><label><?=e(__t('common.reference','Reference'))?> *</label><input name="reference" value="<?=e($p['reference'])?>" required></div><div><label><?=e(__t('common.status','Status'))?></label><select name="status"><?php foreach(['draft','active','sold','rented','withdrawn'] as $s):?><option value="<?=$s?>" <?=$p['status']===$s?'selected':''?>><?=e(ucfirst($s))?></option><?php endforeach;?></select></div><div><label><?=e(__t('common.transaction','Transaction'))?></label><select name="transaction_type"><option value="sale" <?=$p['transaction_type']==='sale'?'selected':''?>>Sale</option><option value="rent" <?=$p['transaction_type']==='rent'?'selected':''?>>Rent</option></select></div><div><label><?=e(__t('common.price','Price'))?></label><input type="number" step="0.01" min="0" name="price" value="<?=e($p['price'])?>"></div>
<div class="span2"><label><?=e(__t('common.title','Title'))?></label><input name="title" value="<?=e($p['title'])?>"></div><div><label>Living area m²</label><input type="number" step="0.01" min="0" name="living_area_m2" value="<?=e($p['living_area_m2'])?>"></div><div><label>Land area m²</label><input type="number" step="0.01" min="0" name="land_area_m2" value="<?=e($p['land_area_m2'])?>"></div><div><label>Bedrooms</label><input type="number" min="0" name="bedrooms" value="<?=e($p['bedrooms'])?>"></div><div><label>Bathrooms</label><input type="number" min="0" name="bathrooms" value="<?=e($p['bathrooms'])?>"></div><div><label>Year built</label><input type="number" min="1000" max="2100" name="year_built" value="<?=e($p['year_built'])?>"></div><div><label>&nbsp;</label><label class="check"><input type="checkbox" name="has_pool" value="1" <?=$p['has_pool']?'checked':''?>> Has pool</label></div><div><label>&nbsp;</label><label class="check"><input type="checkbox" name="is_featured" value="1" <?=$p['is_featured']?'checked':''?>> Featured</label></div><div><label>&nbsp;</label><label class="check"><input type="checkbox" name="is_published" value="1" <?=$p['is_published']?'checked':''?> <?= $role==='agent'?'disabled':''?>> Published</label></div>
<div class="span4"><label>Address</label><input name="address_line_1" value="<?=e($p['address_line_1'])?>"></div><div><label>Address line 2</label><input name="address_line_2" value="<?=e($p['address_line_2'])?>"></div><div><label>Postcode</label><input name="postcode" value="<?=e($p['postcode'])?>"></div><div><label>City</label><input name="city" value="<?=e($p['city'])?>"></div><div><label>Region</label><input name="region" value="<?=e($p['region'])?>"></div><div class="span4"><label>Description</label><textarea name="description"><?=e($p['description'])?></textarea></div></div><div class="actions"><button name="save_property" value="1"><?=e(__t('common.save','Save property'))?></button></div></form></div>
<div class="card" id="photos"><h2><?=e(__t('properties.photos','Photos'))?></h2><div class="upload"><form method="post" action="property-media-upload.php" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="property_id" value="<?=$propertyId?>"><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple required><button type="submit">Upload photos</button><div class="muted">JPG, PNG or WebP · maximum 12 MB per image</div></form></div>
<div class="media-grid" id="mediaGrid"><?php foreach($media as $m): ?><div class="media <?= $m['is_primary']?'primary':'' ?>"><?php if($m['is_primary']): ?><span class="badge">PRIMARY</span><?php endif; ?><img src="<?=e('/immobilier/'.$m['file_path'])?>" alt="<?=e($m['alt_text']??$m['original_filename']??'Property photo')?>"><div class="media-body"><div class="muted"><?=e($m['original_filename']??'photo')?> · <?=e((string)$m['width'])?>×<?=e((string)$m['height'])?></div><form method="post" action="property-media-action.php"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="property_id" value="<?=$propertyId?>"><input type="hidden" name="media_id" value="<?=e($m['id'])?>"><input name="alt_text" value="<?=e($m['alt_text'])?>" placeholder="Alt text"><div class="media-actions"><button name="action" value="primary">Primary</button><button name="action" value="save_alt">Save</button><button name="action" value="delete" onclick="return confirm('Delete this photo?')">Delete</button></div></form></div></div><?php endforeach; ?></div><?php if(!$media): ?><div class="muted">No photos yet.</div><?php endif; ?></div></div></div></body></html>
