<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$auth->requireLogin();
function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$base=rtrim((string)($config['app']['base_url']??'/immobilier'),'/');
$userId=$auth->id(); $officeId=$auth->officeId(); $role=(string)$auth->role();
$u=$db->prepare('SELECT u.first_name,u.last_name,u.email,o.id office_id,o.name office_name FROM users u LEFT JOIN offices o ON o.id=u.office_id AND o.deleted_at IS NULL WHERE u.id=:id AND u.deleted_at IS NULL LIMIT 1');
$u->execute(['id'=>$userId]); $user=$u->fetch()?:[];
$officeName=trim((string)($user['office_name']??'')); if($officeName==='') $officeName=$auth->isSuperAdmin()?'Platform':'Office';
$allowed=['fr','en','nl']; $lang='en'; $langStmt=$db->prepare('SELECT l.code FROM users u LEFT JOIN i18n_languages l ON l.id=u.preferred_language_id AND l.is_active=1 WHERE u.id=:id AND u.deleted_at IS NULL LIMIT 1'); $langStmt->execute(['id'=>$userId]); $dbLang=strtolower(trim((string)$langStmt->fetchColumn())); if(in_array($dbLang,$allowed,true)) $lang=$dbLang;
$t=['en'=>['overview'=>'Properties','manage'=>'Manage your property portfolio','new'=>'New property','search'=>'Search properties…','all'=>'All statuses','published'=>'Published','draft'=>'Draft','archived'=>'Archived','all_types'=>'All transactions','sale'=>'Sale','rent'=>'Rent','property'=>'Property','location'=>'Location','price'=>'Price','details'=>'Details','status'=>'Status','updated'=>'Updated','actions'=>'Actions','edit'=>'Edit','delete'=>'Delete','confirm'=>'Delete this property?','no'=>'No properties found','no_text'=>'Try changing your search or create your first property.','total'=>'Total','active'=>'Published','drafts'=>'Drafts','sales'=>'For sale','rentals'=>'For rent','employees'=>'Employees','sign_out'=>'Sign out','language'=>'Language'], 'fr'=>['overview'=>'Biens','manage'=>'Gérez le portefeuille de votre agence','new'=>'Nouveau bien','search'=>'Rechercher…','all'=>'Tous les statuts','published'=>'Publié','draft'=>'Brouillon','archived'=>'Archivé','all_types'=>'Toutes les transactions','sale'=>'Vente','rent'=>'Location','property'=>'Bien','location'=>'Localisation','price'=>'Prix','details'=>'Détails','status'=>'Statut','updated'=>'Modifié','actions'=>'Actions','edit'=>'Modifier','delete'=>'Supprimer','confirm'=>'Supprimer ce bien ?','no'=>'Aucun bien trouvé','no_text'=>'Modifiez votre recherche ou créez votre premier bien.','total'=>'Total','active'=>'Publiés','drafts'=>'Brouillons','sales'=>'À vendre','rentals'=>'À louer','employees'=>'Employés','sign_out'=>'Déconnexion','language'=>'Langue'], 'nl'=>['overview'=>'Properties','manage'=>'Beheer de vastgoedportefeuille van je kantoor','new'=>'Nieuwe property','search'=>'Properties zoeken…','all'=>'Alle statussen','published'=>'Gepubliceerd','draft'=>'Concept','archived'=>'Gearchiveerd','all_types'=>'Alle transacties','sale'=>'Verkoop','rent'=>'Verhuur','property'=>'Property','location'=>'Locatie','price'=>'Prijs','details'=>'Details','status'=>'Status','updated'=>'Gewijzigd','actions'=>'Acties','edit'=>'Bewerken','delete'=>'Verwijderen','confirm'=>'Deze property verwijderen?','no'=>'Geen properties gevonden','no_text'=>'Pas je zoekopdracht aan of maak je eerste property aan.','total'=>'Totaal','active'=>'Gepubliceerd','drafts'=>'Concepten','sales'=>'Te koop','rentals'=>'Te huur','employees'=>'Medewerkers','sign_out'=>'Uitloggen','language'=>'Taal']][$lang];
$q=trim((string)($_GET['q']??'')); $status=(string)($_GET['status']??''); $transaction=(string)($_GET['transaction']??''); if(!in_array($status,['draft','published','archived'],true))$status=''; if(!in_array($transaction,['sale','rent'],true))$transaction='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='delete'){try{
  \App\Csrf::verify($_POST['_csrf']??''); $pid=(int)($_POST['property_id']??0); if($pid<1)throw new RuntimeException('Invalid property.');
  $sql='SELECT id FROM properties WHERE id=:id AND deleted_at IS NULL';$p=['id'=>$pid]; if(!$auth->isSuperAdmin()){$sql.=' AND office_id=:office_id';$p['office_id']=(int)$officeId;} $s=$db->prepare($sql.' LIMIT 1');$s->execute($p);if(!$s->fetchColumn())throw new RuntimeException('Property not found or access denied.');
  $s=$db->prepare('UPDATE properties SET deleted_at=NOW() WHERE id=:id LIMIT 1');$s->execute(['id'=>$pid]);header('Location: '.$base.'/views/properties.php?deleted=1');exit;
}catch(Throwable $ex){$error=$ex->getMessage();}}
$where=['p.deleted_at IS NULL'];$params=[];if(!$auth->isSuperAdmin()){if(!$officeId){http_response_code(403);exit('No office is assigned to this account.');}$where[]='p.office_id=:office_id';$params['office_id']=(int)$officeId;}
if($q!==''){$where[]='(p.reference LIKE :q OR p.title LIKE :q OR p.city LIKE :q OR o.name LIKE :q)';$params['q']='%'.$q.'%';}if($status!==''){$where[]='p.status=:status';$params['status']=$status;}if($transaction!==''){$where[]='p.transaction_type=:transaction';$params['transaction']=$transaction;}
$sql='SELECT p.id,p.reference,p.status,p.transaction_type,p.title,p.price,p.currency_code,p.living_area_m2,p.land_area_m2,p.bedrooms,p.bathrooms,p.city,p.postcode,p.updated_at,o.name office_name,pt.code property_type,pm.file_path primary_image,pm.thumbnail_path primary_thumbnail FROM properties p INNER JOIN offices o ON o.id=p.office_id LEFT JOIN property_types pt ON pt.id=p.property_type_id LEFT JOIN property_media pm ON pm.id=(SELECT pm2.id FROM property_media pm2 WHERE pm2.property_id=p.id AND pm2.media_type="photo" AND pm2.deleted_at IS NULL ORDER BY pm2.is_primary DESC,pm2.sort_order ASC,pm2.id ASC LIMIT 1) WHERE '.implode(' AND ',$where).' ORDER BY p.updated_at DESC,p.id DESC';$s=$db->prepare($sql);$s->execute($params);$properties=$s->fetchAll();
$countWhere=['p.deleted_at IS NULL'];$cp=[];if(!$auth->isSuperAdmin()){$countWhere[]='p.office_id=:coffice';$cp['coffice']=(int)$officeId;}$count=$db->prepare('SELECT COUNT(*) FROM properties p WHERE '.implode(' AND ',$countWhere));$count->execute($cp);$total=(int)$count->fetchColumn();$pub=$db->prepare('SELECT COUNT(*) FROM properties p WHERE '.implode(' AND ',$countWhere).' AND p.is_published=1');$pub->execute($cp);$published=(int)$pub->fetchColumn();$dr=$db->prepare('SELECT COUNT(*) FROM properties p WHERE '.implode(' AND ',$countWhere)." AND p.status='draft'");$dr->execute($cp);$drafts=(int)$dr->fetchColumn();$sa=$db->prepare('SELECT COUNT(*) FROM properties p WHERE '.implode(' AND ',$countWhere)." AND p.transaction_type='sale'");$sa->execute($cp);$sales=(int)$sa->fetchColumn();$re=$db->prepare('SELECT COUNT(*) FROM properties p WHERE '.implode(' AND ',$countWhere)." AND p.transaction_type='rent'");$re->execute($cp);$rentals=(int)$re->fetchColumn();
$csrf=\App\Csrf::token();$initials=strtoupper(substr((string)($user['first_name']??'U'),0,1).substr((string)($user['last_name']??''),0,1));$image=function(array $p)use($base):?string{$x=trim((string)($p['primary_thumbnail']??''))?:trim((string)($p['primary_image']??''));if($x==='')return null;if(preg_match('~^(https?:)?//~i',$x))return $x;if(str_starts_with($x,'/'))return $x;return $base.'/'.ltrim($x,'/');};
?>
<!doctype html><html lang="<?=e($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($t['property'])?> — <?=e($officeName)?></title><link rel="stylesheet" href="<?=e($base)?>/assets/css/dashboard.css"><link rel="stylesheet" href="<?=e($base)?>/assets/css/properties.css"><style>.transaction-stat-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:9px}.transaction-stat-grid>div+div{border-left:1px solid #edf0f2;padding-left:18px}.transaction-stat-grid strong{margin:0 0 4px}.transaction-stat-grid small{display:block}@media(max-width:760px){.transaction-stat-grid{gap:10px}.transaction-stat-grid>div+div{padding-left:10px}}</style></head><body><div class="app-shell"><?php require __DIR__ . '/../admin/_sidebar.php'; ?><main class="main">
<section class="property-heading"><div><span class="eyebrow"><?=e($t['overview'])?></span><h2><?=e($t['property'])?></h2><p><?=e($t['manage'])?></p></div><a class="button-primary" href="<?=e($base)?>/admin/property-edit.php">+ <?=e($t['new'])?></a></section>
<section class="stats"><div class="stat"><span><?=e($t['total'])?></span><strong><?=$total?></strong><small><?=e($t['property'])?></small></div><div class="stat"><span><?=e($t['active'])?></span><strong><?=$published?></strong><small><?=e($t['published'])?></small></div><div class="stat"><span><?=e($t['drafts'])?></span><strong><?=$drafts?></strong><small><?=e($t['draft'])?></small></div><div class="stat transaction-stat"><span><?=e(__t('properties.transactions','Transactions'))?></span><div class="transaction-stat-grid"><div><strong><?=$sales?></strong><small><?=e($t['sales'])?></small></div><div><strong><?=$rentals?></strong><small><?=e($t['rentals'])?></small></div></div></div></section>
<form class="property-filters" method="get"><input type="hidden" name="lang" value="<?=e($lang)?>"><input class="search" type="search" name="q" value="<?=e($q)?>" placeholder="<?=e($t['search'])?>"><select name="status"><option value=""><?=e($t['all'])?></option><option value="published" <?=$status==='published'?'selected':''?>><?=e($t['published'])?></option><option value="draft" <?=$status==='draft'?'selected':''?>><?=e($t['draft'])?></option><option value="archived" <?=$status==='archived'?'selected':''?>><?=e($t['archived'])?></option></select><select name="transaction"><option value=""><?=e($t['all_types'])?></option><option value="sale" <?=$transaction==='sale'?'selected':''?>><?=e($t['sale'])?></option><option value="rent" <?=$transaction==='rent'?'selected':''?>><?=e($t['rent'])?></option></select><button type="submit"><?=e(__t('common.filter','Filter'))?></button><?php if($q||$status||$transaction):?><a class="clear" href="?lang=<?=e($lang)?>"><?=e(__t('common.clear','Clear'))?></a><?php endif;?></form>
<div class="table-card"><div class="table-scroll"><table class="property-table"><thead><tr><th><?=e($t['property'])?></th><th><?=e($t['location'])?></th><th><?=e($t['price'])?></th><th><?=e($t['details'])?></th><th><?=e($t['status'])?></th><th><?=e($t['updated'])?></th><th></th></tr></thead><tbody><?php foreach($properties as $p):$img=$image($p);?><tr><td><div class="property-cell"><a class="property-thumb" href="<?=e($base)?>/admin/property-edit.php?id=<?=(int)$p['id']?>"><?php if($img):?><img src="<?=e($img)?>" alt=""><?php else:?><span>⌂</span><?php endif;?></a><div><a class="property-title" href="<?=e($base)?>/admin/property-edit.php?id=<?=(int)$p['id']?>"><?=e((string)($p['title']?:$p['reference']))?></a><span class="property-ref"><?=e((string)$p['reference'])?> · <?=e(__t('property_type.'.(string)($p['property_type']?:'other'), (string)($p['property_type']?:'Property')))?></span></div></div></td><td><?=e(trim((string)($p['postcode']??'').' '.(string)($p['city']??'')))?:'—'?></td><td class="price"><?=$p['price']!==null?e(number_format((float)$p['price'],0,',',' ')).' '.e((string)($p['currency_code']?:'EUR')):'—'?></td><td><span class="details"><?=e((string)($p['living_area_m2']??'—'))?> m²<?php if($p['bedrooms']!==null):?> · <?=e((string)$p['bedrooms'])?> bd<?php endif;?></span></td><td><span class="status-pill <?=e((string)$p['status'])?>"><?=e($p['is_published']?__t('properties.published','Published'):__t('properties.status.'.(string)$p['status'],ucfirst((string)$p['status'])))?></span></td><td><?=e(date('d/m/Y',strtotime((string)$p['updated_at'])))?></td><td><div class="actions"><a class="edit" href="<?=e($base)?>/admin/property-edit.php?id=<?=(int)$p['id']?>"><?=e($t['edit'])?></a><form method="post" onsubmit="return confirm('<?=e($t['confirm'])?>');"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="property_id" value="<?=(int)$p['id']?>"><button class="delete" type="submit"><?=e($t['delete'])?></button></form></div></td></tr><?php endforeach;?></tbody></table><?php if(!$properties):?><div class="empty"><strong><?=e($t['no'])?></strong><span><?=e($t['no_text'])?></span></div><?php endif;?></div></div>
</main></div></body></html>
