<?php require __DIR__.'/layouts/header.php'; $p=$property ?? []; $isNew=!$p; ?>
<div class="page-head"><div><a class="back" href="/properties">← <?= htmlspecialchars($i18n->t('back_properties')) ?></a><h1><?= htmlspecialchars($isNew?$i18n->t('new_property'):$p['title']) ?></h1><p class="muted"><?= htmlspecialchars($isNew?$i18n->t('create_property_help'):$p['reference_code']) ?></p></div><div id="saveState" class="save-state"></div></div>
<form id="propertyForm" class="editor-grid">
<input type="hidden" name="id" value="<?= (int)($p['id']??0) ?>">
<section class="card form-card"><div class="section-head"><div><h2><?= htmlspecialchars($i18n->t('property_details')) ?></h2><p><?= htmlspecialchars($i18n->t('property_details_help')) ?></p></div></div>
<div class="form-grid">
<label><?= htmlspecialchars($i18n->t('reference')) ?><input required name="reference_code" value="<?= htmlspecialchars($p['reference_code']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('title')) ?><input required name="title" value="<?= htmlspecialchars($p['title']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('transaction')) ?><select name="transaction_type"><option value="sale" <?= ($p['transaction_type']??'sale')==='sale'?'selected':'' ?>><?= htmlspecialchars($i18n->t('sale')) ?></option><option value="rent" <?= ($p['transaction_type']??'')==='rent'?'selected':'' ?>><?= htmlspecialchars($i18n->t('rent')) ?></option></select></label>
<label><?= htmlspecialchars($i18n->t('status')) ?><select name="listing_status"><?php foreach(['draft','published','under_offer','sold','rented','archived'] as $s): ?><option value="<?= $s ?>" <?= ($p['listing_status']??'draft')===$s?'selected':'' ?>><?= htmlspecialchars($i18n->t($s)) ?></option><?php endforeach; ?></select></label>
<label><?= htmlspecialchars($i18n->t('property_type')) ?><input name="property_type" value="<?= htmlspecialchars($p['property_type']??'house') ?>"></label>
<label><?= htmlspecialchars($i18n->t('price')) ?><input type="number" step="0.01" name="price" value="<?= htmlspecialchars($p['price']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('living_area')) ?><input type="number" step="0.01" name="living_area_m2" value="<?= htmlspecialchars($p['living_area_m2']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('land_area')) ?><input type="number" step="0.01" name="land_area_m2" value="<?= htmlspecialchars($p['land_area_m2']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('bedrooms')) ?><input type="number" min="0" name="bedrooms" value="<?= htmlspecialchars($p['bedrooms']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('bathrooms')) ?><input type="number" min="0" name="bathrooms" value="<?= htmlspecialchars($p['bathrooms']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('office')) ?><select required id="office" name="office_id"><option value=""><?= htmlspecialchars($i18n->t('select_office')) ?></option><?php foreach($offices as $o): ?><option value="<?= (int)$o['id'] ?>" <?= (int)($p['office_id']??0)===(int)$o['id']?'selected':'' ?>><?= htmlspecialchars($o['name']) ?></option><?php endforeach; ?></select></label>
<label><?= htmlspecialchars($i18n->t('agent')) ?><select required id="agent" name="agent_id"><option value=""><?= htmlspecialchars($i18n->t('select_agent')) ?></option><?php foreach($agents as $a): ?><option value="<?= (int)$a['id'] ?>" <?= (int)($p['agent_id']??0)===(int)$a['id']?'selected':'' ?>><?= htmlspecialchars($a['first_name'].' '.$a['last_name']) ?></option><?php endforeach; ?></select></label>
<label><?= htmlspecialchars($i18n->t('city')) ?><input name="city" value="<?= htmlspecialchars($p['city']??'') ?>"></label>
<label><?= htmlspecialchars($i18n->t('postal_code')) ?><input name="postal_code" value="<?= htmlspecialchars($p['postal_code']??'') ?>"></label>
<label class="full"><?= htmlspecialchars($i18n->t('address')) ?><input name="address_line1" value="<?= htmlspecialchars($p['address_line1']??'') ?>"></label>
<label class="full"><?= htmlspecialchars($i18n->t('description')) ?><textarea name="description" rows="9"><?= htmlspecialchars($p['description']??'') ?></textarea></label>
</div></section>
<section class="card photos-card"><div class="section-head"><div><h2><?= htmlspecialchars($i18n->t('photos')) ?></h2><p><?= htmlspecialchars($i18n->t('photos_help')) ?></p></div><?php if(!$isNew): ?><label class="button primary upload-button">+ <?= htmlspecialchars($i18n->t('add_photos')) ?><input id="photoInput" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden></label><?php endif; ?></div>
<?php if($isNew): ?><div class="photo-drop disabled"><div class="drop-icon">✦</div><strong><?= htmlspecialchars($i18n->t('save_before_photos')) ?></strong><span><?= htmlspecialchars($i18n->t('save_before_photos_help')) ?></span></div><?php else: ?><div id="photoGrid" class="photo-grid"><?php foreach($p['photos'] as $photo): ?><div class="photo-item" draggable="true" data-id="<?= (int)$photo['id'] ?>"><img src="<?= htmlspecialchars($photo['file_path']) ?>" alt=""><div class="photo-overlay"><button type="button" class="icon-button hero <?= $photo['is_hero']?'active':'' ?>" title="<?= htmlspecialchars($i18n->t('set_hero')) ?>">★</button><button type="button" class="icon-button delete" title="<?= htmlspecialchars($i18n->t('delete')) ?>">×</button></div><?php if($photo['is_hero']): ?><span class="hero-label">★ <?= htmlspecialchars($i18n->t('hero')) ?></span><?php endif; ?></div><?php endforeach; ?></div><div id="dropZone" class="photo-drop"><div class="drop-icon">↥</div><strong><?= htmlspecialchars($i18n->t('drop_photos')) ?></strong><span><?= htmlspecialchars($i18n->t('drop_photos_help')) ?></span></div><?php endif; ?></section>
<div class="editor-actions"><a class="button" href="/properties"><?= htmlspecialchars($i18n->t('cancel')) ?></a><button class="button primary" type="submit">✓ <?= htmlspecialchars($i18n->t('save_property')) ?></button></div>
</form>
<script>window.IMMO={propertyId:<?= (int)($p['id']??0) ?>,savedHero:<?= json_encode((bool)array_filter($p['photos']??[],fn($x)=>(int)$x['is_hero']===1)) ?>};</script>
<script src="/assets/js/property-editor.js"></script>
<?php require __DIR__.'/layouts/footer.php'; ?>
